version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build -t invicta_fastapi_ecr:latest .
      - docker tag invicta_fastapi_ecr:latest 541816666728.dkr.ecr.ap-southeast-1.amazonaws.com/invicta_fastapi_ecr:latest
  post_build:
    commands:
      - docker push 541816666728.dkr.ecr.ap-southeast-1.amazonaws.com/invicta_fastapi_ecr:latest
      - printf '[{"name":invicta-fastapi-td,"imageUri":"%s"}]' 541816666728.dkr.ecr.ap-southeast-1.amazonaws.com/invicta_fastapi_ecr:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
